repos:
-   repo: https://github.com/psf/black
    rev: refs/tags/23.3.0:refs/tags/23.3.0  # https://github.com/psf/black/issues/2493
    hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.260'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]